### ISSUE TITLE
FPS Counter not Working

### ISSUE THREAD

**Issue by philw95** [BarRaider/streamdeck-shadowplay#15]
Hello the FPS Counter not Working.

It display only FPS
![Image1](https://xbackbone.pkhw.de/36ed1/fuwoRIyoZo154.png/raw)

The FPS Counter is on.
![Image2](https://xbackbone.pkhw.de/36ed1/qEfeDoDEzi972.png/raw)

Stream Deck Version: 4.3.3.11845
ShadowPlay Plugin: 1.2 - 02.10.2019
Graphic Card Driver: 436.48
Geforce Experience: 3.20.0.118

**Comment by Crypto90** [comment]
Does not work for me too.

**Comment by BarRaider** [comment]
Hi,

This key does not display the FPS on the Stream Defk, NVIDIA does not support this feature. The key enables/disables showing the FPS on screen

**Comment by philw95** [comment]
Oh, okay. Then I misunderstood.
Sorry.

Too bad. ^^

BTW: You have made a lot of nice practical plugins. Thanks for your work.

**Comment by BarRaider** [comment]
Yeah, unfortunately getting feedback from ShadowPlay is not supported.
I've asked them for this feature so I hope they'll add it in the future

**Comment by philw95** [comment]
Yes, I hope too.
That would be really great.
