### ISSUE TITLE
All Buttons Perform Save Clip Action

### ISSUE THREAD

**Issue by danieljimenez** [BarRaider/streamdeck-shadowplay#2]
Hi, every button I add to my streamdeck does the same thing... saves a clip. Regardless of which action I drag. Any ideas?

**Comment by BarRaider** [comment]
Sounds like you have a problem in your ShadowPlay configuration. Open the ShadowPlay overlay (usually alt-z) and reassign the keyboard shortcuts

**Comment by danieljimenez** [comment]
Does it have to use the default shortcuts?

**Comment by BarRaider** [comment]
No, you can modify them. But also from the ShadowPlay overlay

**Comment by danieljimenez** [comment]
Got it, thanks!!
